name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build importer
        run: npm run build:importer
      - name: Build library
        run: npm run build:lib
      - name: Lint importer
        run: npm run lint -w importer
      - name: Test importer
        run: npm run test -w importer --if-present

