name: Release Library

on:
  push:
    tags:
      - 'iana-registry-data-lib@*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Build library
        run: npm run build:lib
      - name: Publish to npm
        run: cd iana-registry-data-lib && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
